services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - kafka
    ports:
      - "50051:50051"
      - "8080:8080"

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - '9092:9092' # internal
      - '9094:9094' # external
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '0@kafka:9099'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9099,EXTERNAL://:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  kafka-init:
    image: confluentinc/cp-kafka:latest
    command: |
      bash -c "
      kafka-topics --create --replication-factor 1 --bootstrap-server kafka:9092 --topic loms.order-events --partitions 2 --if-not-exists
      "
    restart: on-failure
    depends_on:
      - kafka

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  postgres:
    container_name: loms_postgres
    image: postgres:17
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - loms_postgres_data:/var/lib/postgresql/data

volumes:
  loms_postgres_data: