// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const decreaseReserveAndTotalCountStock = `-- name: DecreaseReserveAndTotalCountStock :exec
UPDATE stocks
SET reserved    = reserved - $1,
    total_count = total_count - $1
WHERE sku_id = $2
`

type DecreaseReserveAndTotalCountStockParams struct {
	Count int64
	SkuID int64
}

func (q *Queries) DecreaseReserveAndTotalCountStock(ctx context.Context, arg DecreaseReserveAndTotalCountStockParams) error {
	_, err := q.db.Exec(ctx, decreaseReserveAndTotalCountStock, arg.Count, arg.SkuID)
	return err
}

const decreaseReservedStock = `-- name: DecreaseReservedStock :exec
UPDATE stocks
SET reserved = reserved - $1
WHERE sku_id = $2
`

type DecreaseReservedStockParams struct {
	Count int64
	SkuID int64
}

func (q *Queries) DecreaseReservedStock(ctx context.Context, arg DecreaseReservedStockParams) error {
	_, err := q.db.Exec(ctx, decreaseReservedStock, arg.Count, arg.SkuID)
	return err
}

const getStockBySku = `-- name: GetStockBySku :one
SELECT sku_id, total_count, reserved
FROM stocks
WHERE sku_id = $1
`

func (q *Queries) GetStockBySku(ctx context.Context, skuID int64) (Stock, error) {
	row := q.db.QueryRow(ctx, getStockBySku, skuID)
	var i Stock
	err := row.Scan(&i.SkuID, &i.TotalCount, &i.Reserved)
	return i, err
}

const increaseReservedStock = `-- name: IncreaseReservedStock :execrows
UPDATE stocks
SET reserved = reserved + $1
WHERE sku_id = $2
`

type IncreaseReservedStockParams struct {
	Count int64
	SkuID int64
}

func (q *Queries) IncreaseReservedStock(ctx context.Context, arg IncreaseReservedStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, increaseReservedStock, arg.Count, arg.SkuID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
