// GRPCCode generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const getStockBySku = `-- name: GetStockBySku :one
SELECT sku_id, total_count, reserved
FROM stocks
WHERE sku_id = $1
`

func (q *Queries) GetStockBySku(ctx context.Context, skuID int64) (Stock, error) {
	row := q.db.QueryRow(ctx, getStockBySku, skuID)
	var i Stock
	err := row.Scan(&i.SkuID, &i.TotalCount, &i.Reserved)
	return i, err
}

const getStocksBySkus = `-- name: GetStocksBySkus :many
SELECT sku_id, total_count, reserved
FROM stocks
WHERE sku_id = ANY($1::bigint[])
`

func (q *Queries) GetStocksBySkus(ctx context.Context, skuIds []int64) ([]Stock, error) {
	rows, err := q.db.Query(ctx, getStocksBySkus, skuIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stock
	for rows.Next() {
		var i Stock
		if err := rows.Scan(&i.SkuID, &i.TotalCount, &i.Reserved); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveStock = `-- name: SaveStock :exec
UPDATE stocks
SET total_count = $1,
    reserved    = $2
WHERE sku_id = $3
`

type SaveStockParams struct {
	TotalCount int64
	Reserved   int64
	SkuID      int64
}

func (q *Queries) SaveStock(ctx context.Context, arg SaveStockParams) error {
	_, err := q.db.Exec(ctx, saveStock, arg.TotalCount, arg.Reserved, arg.SkuID)
	return err
}
