// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/shizakira/loms/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewOrderStorage creates a new instance of OrderStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderStorage {
	mock := &OrderStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderStorage is an autogenerated mock type for the OrderStorage type
type OrderStorage struct {
	mock.Mock
}

type OrderStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderStorage) EXPECT() *OrderStorage_Expecter {
	return &OrderStorage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type OrderStorage
func (_mock *OrderStorage) Create(ctx context.Context, order domain.Order) (domain.Order, error) {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Order) (domain.Order, error)); ok {
		return returnFunc(ctx, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Order) domain.Order); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Order) error); ok {
		r1 = returnFunc(ctx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderStorage_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderStorage_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx
//   - order
func (_e *OrderStorage_Expecter) Create(ctx interface{}, order interface{}) *OrderStorage_Create_Call {
	return &OrderStorage_Create_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *OrderStorage_Create_Call) Run(run func(ctx context.Context, order domain.Order)) *OrderStorage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Order))
	})
	return _c
}

func (_c *OrderStorage_Create_Call) Return(order1 domain.Order, err error) *OrderStorage_Create_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *OrderStorage_Create_Call) RunAndReturn(run func(ctx context.Context, order domain.Order) (domain.Order, error)) *OrderStorage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type OrderStorage
func (_mock *OrderStorage) GetByID(ctx context.Context, orderID int) (domain.Order, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (domain.Order, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) domain.Order); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderStorage_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type OrderStorage_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx
//   - orderID
func (_e *OrderStorage_Expecter) GetByID(ctx interface{}, orderID interface{}) *OrderStorage_GetByID_Call {
	return &OrderStorage_GetByID_Call{Call: _e.mock.On("GetByID", ctx, orderID)}
}

func (_c *OrderStorage_GetByID_Call) Run(run func(ctx context.Context, orderID int)) *OrderStorage_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *OrderStorage_GetByID_Call) Return(order domain.Order, err error) *OrderStorage_GetByID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderStorage_GetByID_Call) RunAndReturn(run func(ctx context.Context, orderID int) (domain.Order, error)) *OrderStorage_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type OrderStorage
func (_mock *OrderStorage) Save(ctx context.Context, order domain.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderStorage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type OrderStorage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx
//   - order
func (_e *OrderStorage_Expecter) Save(ctx interface{}, order interface{}) *OrderStorage_Save_Call {
	return &OrderStorage_Save_Call{Call: _e.mock.On("Save", ctx, order)}
}

func (_c *OrderStorage_Save_Call) Run(run func(ctx context.Context, order domain.Order)) *OrderStorage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Order))
	})
	return _c
}

func (_c *OrderStorage_Save_Call) Return(err error) *OrderStorage_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderStorage_Save_Call) RunAndReturn(run func(ctx context.Context, order domain.Order) error) *OrderStorage_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewStockStorage creates a new instance of StockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *StockStorage {
	mock := &StockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StockStorage is an autogenerated mock type for the StockStorage type
type StockStorage struct {
	mock.Mock
}

type StockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *StockStorage) EXPECT() *StockStorage_Expecter {
	return &StockStorage_Expecter{mock: &_m.Mock}
}

// GetBySkuID provides a mock function for the type StockStorage
func (_mock *StockStorage) GetBySkuID(ctx context.Context, skus uint32) (domain.Stock, error) {
	ret := _mock.Called(ctx, skus)

	if len(ret) == 0 {
		panic("no return value specified for GetBySkuID")
	}

	var r0 domain.Stock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) (domain.Stock, error)); ok {
		return returnFunc(ctx, skus)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) domain.Stock); ok {
		r0 = returnFunc(ctx, skus)
	} else {
		r0 = ret.Get(0).(domain.Stock)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = returnFunc(ctx, skus)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StockStorage_GetBySkuID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySkuID'
type StockStorage_GetBySkuID_Call struct {
	*mock.Call
}

// GetBySkuID is a helper method to define mock.On call
//   - ctx
//   - skus
func (_e *StockStorage_Expecter) GetBySkuID(ctx interface{}, skus interface{}) *StockStorage_GetBySkuID_Call {
	return &StockStorage_GetBySkuID_Call{Call: _e.mock.On("GetBySkuID", ctx, skus)}
}

func (_c *StockStorage_GetBySkuID_Call) Run(run func(ctx context.Context, skus uint32)) *StockStorage_GetBySkuID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *StockStorage_GetBySkuID_Call) Return(stock domain.Stock, err error) *StockStorage_GetBySkuID_Call {
	_c.Call.Return(stock, err)
	return _c
}

func (_c *StockStorage_GetBySkuID_Call) RunAndReturn(run func(ctx context.Context, skus uint32) (domain.Stock, error)) *StockStorage_GetBySkuID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySkuIDs provides a mock function for the type StockStorage
func (_mock *StockStorage) GetBySkuIDs(ctx context.Context, skus []uint32) ([]domain.Stock, error) {
	ret := _mock.Called(ctx, skus)

	if len(ret) == 0 {
		panic("no return value specified for GetBySkuIDs")
	}

	var r0 []domain.Stock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint32) ([]domain.Stock, error)); ok {
		return returnFunc(ctx, skus)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint32) []domain.Stock); ok {
		r0 = returnFunc(ctx, skus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Stock)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uint32) error); ok {
		r1 = returnFunc(ctx, skus)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StockStorage_GetBySkuIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySkuIDs'
type StockStorage_GetBySkuIDs_Call struct {
	*mock.Call
}

// GetBySkuIDs is a helper method to define mock.On call
//   - ctx
//   - skus
func (_e *StockStorage_Expecter) GetBySkuIDs(ctx interface{}, skus interface{}) *StockStorage_GetBySkuIDs_Call {
	return &StockStorage_GetBySkuIDs_Call{Call: _e.mock.On("GetBySkuIDs", ctx, skus)}
}

func (_c *StockStorage_GetBySkuIDs_Call) Run(run func(ctx context.Context, skus []uint32)) *StockStorage_GetBySkuIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint32))
	})
	return _c
}

func (_c *StockStorage_GetBySkuIDs_Call) Return(stocks []domain.Stock, err error) *StockStorage_GetBySkuIDs_Call {
	_c.Call.Return(stocks, err)
	return _c
}

func (_c *StockStorage_GetBySkuIDs_Call) RunAndReturn(run func(ctx context.Context, skus []uint32) ([]domain.Stock, error)) *StockStorage_GetBySkuIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type StockStorage
func (_mock *StockStorage) Save(ctx context.Context, stock domain.Stock) error {
	ret := _mock.Called(ctx, stock)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Stock) error); ok {
		r0 = returnFunc(ctx, stock)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StockStorage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type StockStorage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx
//   - stock
func (_e *StockStorage_Expecter) Save(ctx interface{}, stock interface{}) *StockStorage_Save_Call {
	return &StockStorage_Save_Call{Call: _e.mock.On("Save", ctx, stock)}
}

func (_c *StockStorage_Save_Call) Run(run func(ctx context.Context, stock domain.Stock)) *StockStorage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Stock))
	})
	return _c
}

func (_c *StockStorage_Save_Call) Return(err error) *StockStorage_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StockStorage_Save_Call) RunAndReturn(run func(ctx context.Context, stock domain.Stock) error) *StockStorage_Save_Call {
	_c.Call.Return(run)
	return _c
}
