// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/shizakira/loms/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewOrderStorage creates a new instance of OrderStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderStorage {
	mock := &OrderStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderStorage is an autogenerated mock type for the OrderStorage type
type OrderStorage struct {
	mock.Mock
}

type OrderStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderStorage) EXPECT() *OrderStorage_Expecter {
	return &OrderStorage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type OrderStorage
func (_mock *OrderStorage) Create(ctx context.Context, order domain.Order) (int, error) {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Order) (int, error)); ok {
		return returnFunc(ctx, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Order) int); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Order) error); ok {
		r1 = returnFunc(ctx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderStorage_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderStorage_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx
//   - order
func (_e *OrderStorage_Expecter) Create(ctx interface{}, order interface{}) *OrderStorage_Create_Call {
	return &OrderStorage_Create_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *OrderStorage_Create_Call) Run(run func(ctx context.Context, order domain.Order)) *OrderStorage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Order))
	})
	return _c
}

func (_c *OrderStorage_Create_Call) Return(n int, err error) *OrderStorage_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *OrderStorage_Create_Call) RunAndReturn(run func(ctx context.Context, order domain.Order) (int, error)) *OrderStorage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type OrderStorage
func (_mock *OrderStorage) GetByID(ctx context.Context, orderID int, pessimistic bool) (domain.Order, error) {
	ret := _mock.Called(ctx, orderID, pessimistic)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) (domain.Order, error)); ok {
		return returnFunc(ctx, orderID, pessimistic)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) domain.Order); ok {
		r0 = returnFunc(ctx, orderID, pessimistic)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, bool) error); ok {
		r1 = returnFunc(ctx, orderID, pessimistic)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderStorage_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type OrderStorage_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx
//   - orderID
//   - pessimistic
func (_e *OrderStorage_Expecter) GetByID(ctx interface{}, orderID interface{}, pessimistic interface{}) *OrderStorage_GetByID_Call {
	return &OrderStorage_GetByID_Call{Call: _e.mock.On("GetByID", ctx, orderID, pessimistic)}
}

func (_c *OrderStorage_GetByID_Call) Run(run func(ctx context.Context, orderID int, pessimistic bool)) *OrderStorage_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(bool))
	})
	return _c
}

func (_c *OrderStorage_GetByID_Call) Return(order domain.Order, err error) *OrderStorage_GetByID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderStorage_GetByID_Call) RunAndReturn(run func(ctx context.Context, orderID int, pessimistic bool) (domain.Order, error)) *OrderStorage_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type OrderStorage
func (_mock *OrderStorage) UpdateStatus(ctx context.Context, orderID int, status domain.OrderStatus) error {
	ret := _mock.Called(ctx, orderID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, domain.OrderStatus) error); ok {
		r0 = returnFunc(ctx, orderID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderStorage_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type OrderStorage_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx
//   - orderID
//   - status
func (_e *OrderStorage_Expecter) UpdateStatus(ctx interface{}, orderID interface{}, status interface{}) *OrderStorage_UpdateStatus_Call {
	return &OrderStorage_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, orderID, status)}
}

func (_c *OrderStorage_UpdateStatus_Call) Run(run func(ctx context.Context, orderID int, status domain.OrderStatus)) *OrderStorage_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(domain.OrderStatus))
	})
	return _c
}

func (_c *OrderStorage_UpdateStatus_Call) Return(err error) *OrderStorage_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderStorage_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, orderID int, status domain.OrderStatus) error) *OrderStorage_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewStockStorage creates a new instance of StockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *StockStorage {
	mock := &StockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StockStorage is an autogenerated mock type for the StockStorage type
type StockStorage struct {
	mock.Mock
}

type StockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *StockStorage) EXPECT() *StockStorage_Expecter {
	return &StockStorage_Expecter{mock: &_m.Mock}
}

// DecreaseReserveAndTotalCount provides a mock function for the type StockStorage
func (_mock *StockStorage) DecreaseReserveAndTotalCount(ctx context.Context, skuID int, count int) error {
	ret := _mock.Called(ctx, skuID, count)

	if len(ret) == 0 {
		panic("no return value specified for DecreaseReserveAndTotalCount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, skuID, count)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StockStorage_DecreaseReserveAndTotalCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecreaseReserveAndTotalCount'
type StockStorage_DecreaseReserveAndTotalCount_Call struct {
	*mock.Call
}

// DecreaseReserveAndTotalCount is a helper method to define mock.On call
//   - ctx
//   - skuID
//   - count
func (_e *StockStorage_Expecter) DecreaseReserveAndTotalCount(ctx interface{}, skuID interface{}, count interface{}) *StockStorage_DecreaseReserveAndTotalCount_Call {
	return &StockStorage_DecreaseReserveAndTotalCount_Call{Call: _e.mock.On("DecreaseReserveAndTotalCount", ctx, skuID, count)}
}

func (_c *StockStorage_DecreaseReserveAndTotalCount_Call) Run(run func(ctx context.Context, skuID int, count int)) *StockStorage_DecreaseReserveAndTotalCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *StockStorage_DecreaseReserveAndTotalCount_Call) Return(err error) *StockStorage_DecreaseReserveAndTotalCount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StockStorage_DecreaseReserveAndTotalCount_Call) RunAndReturn(run func(ctx context.Context, skuID int, count int) error) *StockStorage_DecreaseReserveAndTotalCount_Call {
	_c.Call.Return(run)
	return _c
}

// DecreaseReserved provides a mock function for the type StockStorage
func (_mock *StockStorage) DecreaseReserved(ctx context.Context, skuID int, count int) error {
	ret := _mock.Called(ctx, skuID, count)

	if len(ret) == 0 {
		panic("no return value specified for DecreaseReserved")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, skuID, count)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StockStorage_DecreaseReserved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecreaseReserved'
type StockStorage_DecreaseReserved_Call struct {
	*mock.Call
}

// DecreaseReserved is a helper method to define mock.On call
//   - ctx
//   - skuID
//   - count
func (_e *StockStorage_Expecter) DecreaseReserved(ctx interface{}, skuID interface{}, count interface{}) *StockStorage_DecreaseReserved_Call {
	return &StockStorage_DecreaseReserved_Call{Call: _e.mock.On("DecreaseReserved", ctx, skuID, count)}
}

func (_c *StockStorage_DecreaseReserved_Call) Run(run func(ctx context.Context, skuID int, count int)) *StockStorage_DecreaseReserved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *StockStorage_DecreaseReserved_Call) Return(err error) *StockStorage_DecreaseReserved_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StockStorage_DecreaseReserved_Call) RunAndReturn(run func(ctx context.Context, skuID int, count int) error) *StockStorage_DecreaseReserved_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySkuID provides a mock function for the type StockStorage
func (_mock *StockStorage) GetBySkuID(ctx context.Context, sku int) (domain.Stock, error) {
	ret := _mock.Called(ctx, sku)

	if len(ret) == 0 {
		panic("no return value specified for GetBySkuID")
	}

	var r0 domain.Stock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (domain.Stock, error)); ok {
		return returnFunc(ctx, sku)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) domain.Stock); ok {
		r0 = returnFunc(ctx, sku)
	} else {
		r0 = ret.Get(0).(domain.Stock)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, sku)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StockStorage_GetBySkuID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySkuID'
type StockStorage_GetBySkuID_Call struct {
	*mock.Call
}

// GetBySkuID is a helper method to define mock.On call
//   - ctx
//   - sku
func (_e *StockStorage_Expecter) GetBySkuID(ctx interface{}, sku interface{}) *StockStorage_GetBySkuID_Call {
	return &StockStorage_GetBySkuID_Call{Call: _e.mock.On("GetBySkuID", ctx, sku)}
}

func (_c *StockStorage_GetBySkuID_Call) Run(run func(ctx context.Context, sku int)) *StockStorage_GetBySkuID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *StockStorage_GetBySkuID_Call) Return(stock domain.Stock, err error) *StockStorage_GetBySkuID_Call {
	_c.Call.Return(stock, err)
	return _c
}

func (_c *StockStorage_GetBySkuID_Call) RunAndReturn(run func(ctx context.Context, sku int) (domain.Stock, error)) *StockStorage_GetBySkuID_Call {
	_c.Call.Return(run)
	return _c
}

// Reserve provides a mock function for the type StockStorage
func (_mock *StockStorage) Reserve(ctx context.Context, skuID int, count int) error {
	ret := _mock.Called(ctx, skuID, count)

	if len(ret) == 0 {
		panic("no return value specified for Reserve")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, skuID, count)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StockStorage_Reserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reserve'
type StockStorage_Reserve_Call struct {
	*mock.Call
}

// Reserve is a helper method to define mock.On call
//   - ctx
//   - skuID
//   - count
func (_e *StockStorage_Expecter) Reserve(ctx interface{}, skuID interface{}, count interface{}) *StockStorage_Reserve_Call {
	return &StockStorage_Reserve_Call{Call: _e.mock.On("Reserve", ctx, skuID, count)}
}

func (_c *StockStorage_Reserve_Call) Run(run func(ctx context.Context, skuID int, count int)) *StockStorage_Reserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *StockStorage_Reserve_Call) Return(err error) *StockStorage_Reserve_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StockStorage_Reserve_Call) RunAndReturn(run func(ctx context.Context, skuID int, count int) error) *StockStorage_Reserve_Call {
	_c.Call.Return(run)
	return _c
}
