// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (status, user_id)
VALUES ($1, $2)
    RETURNING id
`

type CreateOrderParams struct {
	Status OrderStatus
	UserID int64
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.Status, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (order_id, sku, count)
VALUES ($1, $2, $3)
`

type CreateOrderItemParams struct {
	OrderID int64
	Sku     int64
	Count   int16
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem, arg.OrderID, arg.Sku, arg.Count)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, status, user_id
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(&i.ID, &i.Status, &i.UserID)
	return i, err
}

const getOrderByIDForUpdate = `-- name: GetOrderByIDForUpdate :one
SELECT id, status, user_id
FROM orders
WHERE id = $1
FOR NO KEY UPDATE
`

func (q *Queries) GetOrderByIDForUpdate(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIDForUpdate, id)
	var i Order
	err := row.Scan(&i.ID, &i.Status, &i.UserID)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT sku, count
FROM order_items
WHERE order_id = $1
`

type GetOrderItemsRow struct {
	Sku   int64
	Count int16
}

func (q *Queries) GetOrderItems(ctx context.Context, orderID int64) ([]GetOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsRow
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(&i.Sku, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $1
WHERE id = $2
`

type UpdateOrderStatusParams struct {
	Status OrderStatus
	ID     int64
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.Status, arg.ID)
	return err
}
